// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: api/grpc/proto/wallet.proto

package wallet_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCreateWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RequestCreateWallet) Reset() {
	*x = RequestCreateWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreateWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateWallet) ProtoMessage() {}

func (x *RequestCreateWallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateWallet.ProtoReflect.Descriptor instead.
func (*RequestCreateWallet) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreateWallet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResponseCreateWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool        `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *DataWallet `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32       `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32       `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string      `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseCreateWallet) Reset() {
	*x = ResponseCreateWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCreateWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateWallet) ProtoMessage() {}

func (x *ResponseCreateWallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateWallet.ProtoReflect.Descriptor instead.
func (*ResponseCreateWallet) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseCreateWallet) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResponseCreateWallet) GetData() *DataWallet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseCreateWallet) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseCreateWallet) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResponseCreateWallet) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DataWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mnemonic string   `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Key      *KeyPair `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DataWallet) Reset() {
	*x = DataWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataWallet) ProtoMessage() {}

func (x *DataWallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataWallet.ProtoReflect.Descriptor instead.
func (*DataWallet) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *DataWallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataWallet) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *DataWallet) GetKey() *KeyPair {
	if x != nil {
		return x.Key
	}
	return nil
}

type KeyPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Public  string `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private string `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *KeyPair) Reset() {
	*x = KeyPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPair) ProtoMessage() {}

func (x *KeyPair) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPair.ProtoReflect.Descriptor instead.
func (*KeyPair) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *KeyPair) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *KeyPair) GetPrivate() string {
	if x != nil {
		return x.Private
	}
	return ""
}

type RequestActivateWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mnemonic string `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
}

func (x *RequestActivateWallet) Reset() {
	*x = RequestActivateWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestActivateWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestActivateWallet) ProtoMessage() {}

func (x *RequestActivateWallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestActivateWallet.ProtoReflect.Descriptor instead.
func (*RequestActivateWallet) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *RequestActivateWallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestActivateWallet) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

type ResponseActivateWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool          `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *WalletActive `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32         `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32         `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string        `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseActivateWallet) Reset() {
	*x = ResponseActivateWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseActivateWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseActivateWallet) ProtoMessage() {}

func (x *ResponseActivateWallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseActivateWallet.ProtoReflect.Descriptor instead.
func (*ResponseActivateWallet) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseActivateWallet) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResponseActivateWallet) GetData() *WalletActive {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseActivateWallet) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseActivateWallet) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResponseActivateWallet) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WalletActive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mnemonic string   `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Key      *KeyPair `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *WalletActive) Reset() {
	*x = WalletActive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletActive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletActive) ProtoMessage() {}

func (x *WalletActive) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletActive.ProtoReflect.Descriptor instead.
func (*WalletActive) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *WalletActive) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WalletActive) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *WalletActive) GetKey() *KeyPair {
	if x != nil {
		return x.Key
	}
	return nil
}

type Wallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mnemonic       string `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Public         string `protobuf:"bytes,3,opt,name=public,proto3" json:"public,omitempty"`
	IpDevice       string `protobuf:"bytes,4,opt,name=ip_device,json=ipDevice,proto3" json:"ip_device,omitempty"`
	StatusId       int32  `protobuf:"varint,5,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	IdentityNumber string `protobuf:"bytes,6,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	CreatedAt      string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *Wallet) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *Wallet) GetIpDevice() string {
	if x != nil {
		return x.IpDevice
	}
	return ""
}

func (x *Wallet) GetStatusId() int32 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *Wallet) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *Wallet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Wallet) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RequestGetWalletById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestGetWalletById) Reset() {
	*x = RequestGetWalletById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetWalletById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetWalletById) ProtoMessage() {}

func (x *RequestGetWalletById) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetWalletById.ProtoReflect.Descriptor instead.
func (*RequestGetWalletById) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *RequestGetWalletById) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResponseGetWalletById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Wallet `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string  `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseGetWalletById) Reset() {
	*x = ResponseGetWalletById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetWalletById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetWalletById) ProtoMessage() {}

func (x *ResponseGetWalletById) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetWalletById.ProtoReflect.Descriptor instead.
func (*ResponseGetWalletById) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseGetWalletById) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResponseGetWalletById) GetData() *Wallet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseGetWalletById) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseGetWalletById) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResponseGetWalletById) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RequestGetWalletByUserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RequestGetWalletByUserId) Reset() {
	*x = RequestGetWalletByUserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetWalletByUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetWalletByUserId) ProtoMessage() {}

func (x *RequestGetWalletByUserId) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetWalletByUserId.ProtoReflect.Descriptor instead.
func (*RequestGetWalletByUserId) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *RequestGetWalletByUserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResponseGetWalletByUserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Wallet `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string  `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseGetWalletByUserId) Reset() {
	*x = ResponseGetWalletByUserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetWalletByUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetWalletByUserId) ProtoMessage() {}

func (x *ResponseGetWalletByUserId) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetWalletByUserId.ProtoReflect.Descriptor instead.
func (*ResponseGetWalletByUserId) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseGetWalletByUserId) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResponseGetWalletByUserId) GetData() *Wallet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseGetWalletByUserId) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseGetWalletByUserId) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResponseGetWalletByUserId) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RqGetByIdentityNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentityNumber string `protobuf:"bytes,1,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
}

func (x *RqGetByIdentityNumber) Reset() {
	*x = RqGetByIdentityNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RqGetByIdentityNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqGetByIdentityNumber) ProtoMessage() {}

func (x *RqGetByIdentityNumber) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqGetByIdentityNumber.ProtoReflect.Descriptor instead.
func (*RqGetByIdentityNumber) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *RqGetByIdentityNumber) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

type ResponseGetByIdentityNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Wallet `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string  `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseGetByIdentityNumber) Reset() {
	*x = ResponseGetByIdentityNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetByIdentityNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetByIdentityNumber) ProtoMessage() {}

func (x *ResponseGetByIdentityNumber) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetByIdentityNumber.ProtoReflect.Descriptor instead.
func (*ResponseGetByIdentityNumber) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseGetByIdentityNumber) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResponseGetByIdentityNumber) GetData() *Wallet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseGetByIdentityNumber) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseGetByIdentityNumber) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResponseGetByIdentityNumber) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RqCreateWalletBySystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentityNumber string `protobuf:"bytes,1,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
}

func (x *RqCreateWalletBySystem) Reset() {
	*x = RqCreateWalletBySystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RqCreateWalletBySystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqCreateWalletBySystem) ProtoMessage() {}

func (x *RqCreateWalletBySystem) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqCreateWalletBySystem.ProtoReflect.Descriptor instead.
func (*RqCreateWalletBySystem) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *RqCreateWalletBySystem) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

type ResponseCreateWalletBySystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool        `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *DataWallet `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32       `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32       `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string      `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseCreateWalletBySystem) Reset() {
	*x = ResponseCreateWalletBySystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCreateWalletBySystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateWalletBySystem) ProtoMessage() {}

func (x *ResponseCreateWalletBySystem) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateWalletBySystem.ProtoReflect.Descriptor instead.
func (*ResponseCreateWalletBySystem) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *ResponseCreateWalletBySystem) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResponseCreateWalletBySystem) GetData() *DataWallet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseCreateWalletBySystem) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseCreateWalletBySystem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResponseCreateWalletBySystem) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RqUpdateWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpDevice       string `protobuf:"bytes,2,opt,name=ip_device,json=ipDevice,proto3" json:"ip_device,omitempty"`
	IdentityNumber string `protobuf:"bytes,3,opt,name=identity_number,json=identityNumber,proto3" json:"identity_number,omitempty"`
	StatusId       int32  `protobuf:"varint,4,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
}

func (x *RqUpdateWallet) Reset() {
	*x = RqUpdateWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RqUpdateWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqUpdateWallet) ProtoMessage() {}

func (x *RqUpdateWallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqUpdateWallet.ProtoReflect.Descriptor instead.
func (*RqUpdateWallet) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *RqUpdateWallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RqUpdateWallet) GetIpDevice() string {
	if x != nil {
		return x.IpDevice
	}
	return ""
}

func (x *RqUpdateWallet) GetIdentityNumber() string {
	if x != nil {
		return x.IdentityNumber
	}
	return ""
}

func (x *RqUpdateWallet) GetStatusId() int32 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

type ResUpdateWallet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *Wallet `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string  `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResUpdateWallet) Reset() {
	*x = ResUpdateWallet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResUpdateWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResUpdateWallet) ProtoMessage() {}

func (x *ResUpdateWallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResUpdateWallet.ProtoReflect.Descriptor instead.
func (*ResUpdateWallet) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{17}
}

func (x *ResUpdateWallet) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResUpdateWallet) GetData() *Wallet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResUpdateWallet) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResUpdateWallet) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResUpdateWallet) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RqFrozenMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletId  string  `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount    float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	LotteryId string  `protobuf:"bytes,3,opt,name=lottery_id,json=lotteryId,proto3" json:"lottery_id,omitempty"`
}

func (x *RqFrozenMoney) Reset() {
	*x = RqFrozenMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RqFrozenMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqFrozenMoney) ProtoMessage() {}

func (x *RqFrozenMoney) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqFrozenMoney.ProtoReflect.Descriptor instead.
func (*RqFrozenMoney) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{18}
}

func (x *RqFrozenMoney) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *RqFrozenMoney) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RqFrozenMoney) GetLotteryId() string {
	if x != nil {
		return x.LotteryId
	}
	return ""
}

type ResFrozenMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResFrozenMoney) Reset() {
	*x = ResFrozenMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResFrozenMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResFrozenMoney) ProtoMessage() {}

func (x *ResFrozenMoney) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResFrozenMoney.ProtoReflect.Descriptor instead.
func (*ResFrozenMoney) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{19}
}

func (x *ResFrozenMoney) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResFrozenMoney) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ResFrozenMoney) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResFrozenMoney) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResFrozenMoney) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RqUnFreezeMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletId  string  `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	LotteryId string  `protobuf:"bytes,2,opt,name=lottery_id,json=lotteryId,proto3" json:"lottery_id,omitempty"`
	Penalty   float64 `protobuf:"fixed64,3,opt,name=penalty,proto3" json:"penalty,omitempty"`
}

func (x *RqUnFreezeMoney) Reset() {
	*x = RqUnFreezeMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RqUnFreezeMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqUnFreezeMoney) ProtoMessage() {}

func (x *RqUnFreezeMoney) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqUnFreezeMoney.ProtoReflect.Descriptor instead.
func (*RqUnFreezeMoney) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{20}
}

func (x *RqUnFreezeMoney) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *RqUnFreezeMoney) GetLotteryId() string {
	if x != nil {
		return x.LotteryId
	}
	return ""
}

func (x *RqUnFreezeMoney) GetPenalty() float64 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

type ResUnFreezeMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResUnFreezeMoney) Reset() {
	*x = ResUnFreezeMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResUnFreezeMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResUnFreezeMoney) ProtoMessage() {}

func (x *ResUnFreezeMoney) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResUnFreezeMoney.ProtoReflect.Descriptor instead.
func (*ResUnFreezeMoney) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{21}
}

func (x *ResUnFreezeMoney) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResUnFreezeMoney) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ResUnFreezeMoney) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResUnFreezeMoney) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResUnFreezeMoney) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RqGetFrozenMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletId string `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
}

func (x *RqGetFrozenMoney) Reset() {
	*x = RqGetFrozenMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RqGetFrozenMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RqGetFrozenMoney) ProtoMessage() {}

func (x *RqGetFrozenMoney) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RqGetFrozenMoney.ProtoReflect.Descriptor instead.
func (*RqGetFrozenMoney) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{22}
}

func (x *RqGetFrozenMoney) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type ResGetFrozenMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  float64 `protobuf:"fixed64,2,opt,name=data,proto3" json:"data,omitempty"`
	Code  int32   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Type  int32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg   string  `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResGetFrozenMoney) Reset() {
	*x = ResGetFrozenMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_wallet_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetFrozenMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetFrozenMoney) ProtoMessage() {}

func (x *ResGetFrozenMoney) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_wallet_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetFrozenMoney.ProtoReflect.Descriptor instead.
func (*ResGetFrozenMoney) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_wallet_proto_rawDescGZIP(), []int{23}
}

func (x *ResGetFrozenMoney) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResGetFrozenMoney) GetData() float64 {
	if x != nil {
		return x.Data
	}
	return 0
}

func (x *ResGetFrozenMoney) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResGetFrozenMoney) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ResGetFrozenMoney) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_grpc_proto_wallet_proto protoreflect.FileDescriptor

var file_api_grpc_proto_wallet_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x13, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x14,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x61, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x12, 0x27, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3b, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x22, 0x43, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x22, 0x98, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x63, 0x0a, 0x0c, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x12, 0x27,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xed, 0x01, 0x0a, 0x06, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x70, 0x5f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x70, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64,
	0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x91, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x33, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65,
	0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x19, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x40, 0x0a, 0x15, 0x52, 0x71, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x1b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x41, 0x0a, 0x16,
	0x52, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x9c, 0x01, 0x0a, 0x1c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x83,
	0x01, 0x0a, 0x0e, 0x52, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x70, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x70, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x28,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x63, 0x0a, 0x0d, 0x52, 0x71, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x46, 0x72,
	0x6f, 0x7a, 0x65, 0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x67, 0x0a,
	0x0f, 0x52, 0x71, 0x55, 0x6e, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6c, 0x6f, 0x74, 0x74, 0x65, 0x72, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x70,
	0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x22, 0x76, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x55, 0x6e, 0x46,
	0x72, 0x65, 0x65, 0x7a, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2f,
	0x0a, 0x10, 0x52, 0x71, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x22,
	0x77, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xaf, 0x07, 0x0a, 0x14, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x12, 0x57, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x12, 0x21, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x22, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0e, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x23, 0x2e, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x1a, 0x24, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x22, 0x2e, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x23,
	0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x2e, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x1a, 0x27, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x00, 0x12, 0x6d, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x71, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a,
	0x29, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x12, 0x24, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x42, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x1a, 0x2a, 0x2e, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x79,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x7a, 0x65,
	0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1b, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x71, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x1a, 0x1c, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x65, 0x73, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x55, 0x6e, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x71, 0x55, 0x6e, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x1a, 0x1e, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x65, 0x73, 0x55, 0x6e, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x7a,
	0x65, 0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1e, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x71, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x7a,
	0x65, 0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x1a, 0x1f, 0x2e, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x65, 0x73, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f,
	0x7a, 0x65, 0x6e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_proto_wallet_proto_rawDescOnce sync.Once
	file_api_grpc_proto_wallet_proto_rawDescData = file_api_grpc_proto_wallet_proto_rawDesc
)

func file_api_grpc_proto_wallet_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_wallet_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_proto_wallet_proto_rawDescData)
	})
	return file_api_grpc_proto_wallet_proto_rawDescData
}

var file_api_grpc_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_grpc_proto_wallet_proto_goTypes = []interface{}{
	(*RequestCreateWallet)(nil),          // 0: wallet_proto.RequestCreateWallet
	(*ResponseCreateWallet)(nil),         // 1: wallet_proto.ResponseCreateWallet
	(*DataWallet)(nil),                   // 2: wallet_proto.DataWallet
	(*KeyPair)(nil),                      // 3: wallet_proto.KeyPair
	(*RequestActivateWallet)(nil),        // 4: wallet_proto.RequestActivateWallet
	(*ResponseActivateWallet)(nil),       // 5: wallet_proto.ResponseActivateWallet
	(*WalletActive)(nil),                 // 6: wallet_proto.WalletActive
	(*Wallet)(nil),                       // 7: wallet_proto.Wallet
	(*RequestGetWalletById)(nil),         // 8: wallet_proto.RequestGetWalletById
	(*ResponseGetWalletById)(nil),        // 9: wallet_proto.ResponseGetWalletById
	(*RequestGetWalletByUserId)(nil),     // 10: wallet_proto.RequestGetWalletByUserId
	(*ResponseGetWalletByUserId)(nil),    // 11: wallet_proto.ResponseGetWalletByUserId
	(*RqGetByIdentityNumber)(nil),        // 12: wallet_proto.RqGetByIdentityNumber
	(*ResponseGetByIdentityNumber)(nil),  // 13: wallet_proto.ResponseGetByIdentityNumber
	(*RqCreateWalletBySystem)(nil),       // 14: wallet_proto.RqCreateWalletBySystem
	(*ResponseCreateWalletBySystem)(nil), // 15: wallet_proto.ResponseCreateWalletBySystem
	(*RqUpdateWallet)(nil),               // 16: wallet_proto.RqUpdateWallet
	(*ResUpdateWallet)(nil),              // 17: wallet_proto.ResUpdateWallet
	(*RqFrozenMoney)(nil),                // 18: wallet_proto.RqFrozenMoney
	(*ResFrozenMoney)(nil),               // 19: wallet_proto.resFrozenMoney
	(*RqUnFreezeMoney)(nil),              // 20: wallet_proto.RqUnFreezeMoney
	(*ResUnFreezeMoney)(nil),             // 21: wallet_proto.resUnFreezeMoney
	(*RqGetFrozenMoney)(nil),             // 22: wallet_proto.RqGetFrozenMoney
	(*ResGetFrozenMoney)(nil),            // 23: wallet_proto.resGetFrozenMoney
}
var file_api_grpc_proto_wallet_proto_depIdxs = []int32{
	2,  // 0: wallet_proto.ResponseCreateWallet.data:type_name -> wallet_proto.DataWallet
	3,  // 1: wallet_proto.DataWallet.key:type_name -> wallet_proto.KeyPair
	6,  // 2: wallet_proto.ResponseActivateWallet.data:type_name -> wallet_proto.WalletActive
	3,  // 3: wallet_proto.WalletActive.key:type_name -> wallet_proto.KeyPair
	7,  // 4: wallet_proto.ResponseGetWalletById.data:type_name -> wallet_proto.Wallet
	7,  // 5: wallet_proto.ResponseGetWalletByUserId.data:type_name -> wallet_proto.Wallet
	7,  // 6: wallet_proto.ResponseGetByIdentityNumber.data:type_name -> wallet_proto.Wallet
	2,  // 7: wallet_proto.ResponseCreateWalletBySystem.data:type_name -> wallet_proto.DataWallet
	7,  // 8: wallet_proto.ResUpdateWallet.data:type_name -> wallet_proto.Wallet
	0,  // 9: wallet_proto.walletServicesWallet.CreateWallet:input_type -> wallet_proto.RequestCreateWallet
	4,  // 10: wallet_proto.walletServicesWallet.ActivateWallet:input_type -> wallet_proto.RequestActivateWallet
	8,  // 11: wallet_proto.walletServicesWallet.GetWalletById:input_type -> wallet_proto.RequestGetWalletById
	10, // 12: wallet_proto.walletServicesWallet.GetWalletByUserId:input_type -> wallet_proto.RequestGetWalletByUserId
	12, // 13: wallet_proto.walletServicesWallet.GetWalletByIdentityNumber:input_type -> wallet_proto.RqGetByIdentityNumber
	14, // 14: wallet_proto.walletServicesWallet.CreateWalletBySystem:input_type -> wallet_proto.RqCreateWalletBySystem
	16, // 15: wallet_proto.walletServicesWallet.UpdateWallet:input_type -> wallet_proto.RqUpdateWallet
	18, // 16: wallet_proto.walletServicesWallet.FrozenMoney:input_type -> wallet_proto.RqFrozenMoney
	20, // 17: wallet_proto.walletServicesWallet.UnFreezeMoney:input_type -> wallet_proto.RqUnFreezeMoney
	22, // 18: wallet_proto.walletServicesWallet.GetFrozenMoney:input_type -> wallet_proto.RqGetFrozenMoney
	1,  // 19: wallet_proto.walletServicesWallet.CreateWallet:output_type -> wallet_proto.ResponseCreateWallet
	5,  // 20: wallet_proto.walletServicesWallet.ActivateWallet:output_type -> wallet_proto.ResponseActivateWallet
	9,  // 21: wallet_proto.walletServicesWallet.GetWalletById:output_type -> wallet_proto.ResponseGetWalletById
	11, // 22: wallet_proto.walletServicesWallet.GetWalletByUserId:output_type -> wallet_proto.ResponseGetWalletByUserId
	13, // 23: wallet_proto.walletServicesWallet.GetWalletByIdentityNumber:output_type -> wallet_proto.ResponseGetByIdentityNumber
	15, // 24: wallet_proto.walletServicesWallet.CreateWalletBySystem:output_type -> wallet_proto.ResponseCreateWalletBySystem
	17, // 25: wallet_proto.walletServicesWallet.UpdateWallet:output_type -> wallet_proto.ResUpdateWallet
	19, // 26: wallet_proto.walletServicesWallet.FrozenMoney:output_type -> wallet_proto.resFrozenMoney
	21, // 27: wallet_proto.walletServicesWallet.UnFreezeMoney:output_type -> wallet_proto.resUnFreezeMoney
	23, // 28: wallet_proto.walletServicesWallet.GetFrozenMoney:output_type -> wallet_proto.resGetFrozenMoney
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_wallet_proto_init() }
func file_api_grpc_proto_wallet_proto_init() {
	if File_api_grpc_proto_wallet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_proto_wallet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreateWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCreateWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestActivateWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseActivateWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletActive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetWalletById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetWalletById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetWalletByUserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetWalletByUserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RqGetByIdentityNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetByIdentityNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RqCreateWalletBySystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCreateWalletBySystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RqUpdateWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResUpdateWallet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RqFrozenMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResFrozenMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RqUnFreezeMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResUnFreezeMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RqGetFrozenMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_wallet_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetFrozenMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_proto_wallet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_wallet_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_wallet_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_wallet_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_wallet_proto = out.File
	file_api_grpc_proto_wallet_proto_rawDesc = nil
	file_api_grpc_proto_wallet_proto_goTypes = nil
	file_api_grpc_proto_wallet_proto_depIdxs = nil
}
